#!/bin/bash

# 检查参数数量
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <code> <param>"
    exit 1
fi

# 分别获取第一个和第二个参数
code=$1
param=$2

# 执行 curl 命令
res=$(curl --data "{\"code\": \"$code\", \"param\": $param}" -s -X POST http://localhost:1976)

node -e "console.log(JSON.stringify($res, null, 4))"

